image: node:10.15.3

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - hexo generate

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master
